<?php






function wc_oei_ajax_import_init() {
	require_once WC_OEI_PLUGIN_DIR . 'includes/admin/class-wc-oei-importer.php';

	$importer = new WC_OEI_Importer;

	$importer->process_import();

	print 'success 123';

	exit;
}


function wc_oei_admin_scripts() {
	wp_register_script( 'wc-oei-admin-proc', WC_OEI_PLUGIN_URL . 'assets/admin/js/wc-oei-admin-processing.js', array( 'jquery' ), WC_OEI_VERSION, false );

	wp_enqueue_style( 'woocommerce_admin_styles' );

	if( isset( $_GET['import'] ) && $_GET['import'] == 'woocommerce_oei_importer' ) {
		wp_enqueue_script( 'wc-oei-admin-proc' );
		wp_enqueue_style( 'media-views' );
		wp_enqueue_style( 'woocommerce_admin_styles' );
	}
}
add_action( 'admin_enqueue_scripts', 'wc_oei_admin_scripts', 15 );

function wc_oei_register_importer() {
	register_importer( 'woocommerce_oei_importer', __( 'WooCommerce orders (JSON)', 'wc-oei' ), __( 'Import orders for you store via JSON.', 'wc-oei' ), 'wc_oei_order_importer_html' );

	add_action( 'wp_ajax_wc_oei_import_processing', 'wc_oei_ajax_import_init' );
}
add_action( 'admin_init', 'wc_oei_register_importer' );


function wc_oei_order_importer_html() {

	$step		= empty( $_GET['step'] ) ? 0 : (int) $_GET['step'];
	$bytes      = apply_filters( 'import_upload_size_limit', wp_max_upload_size() );
	$size       = size_format( $bytes );
	$upload_dir = wp_upload_dir();
?>

<div class="wrap">
	<h2><?php _e( 'Import orders', 'wc-oei' ); ?></h2>
	<div class="wc-oei-admin wc-oei-importer">
		<?php if( $step === 0 ) : ?>

			<p><?php _e( 'Upload the JSON file which was generated by exporting existing orders using this plugin.', 'wc-oei' ); ?></p>

			<?php if( ! empty( $upload_dir['error'] ) ) : ?>
				
				<div class="error">
					<p><?php _e('Before you can upload your import file, you will need to fix the following error:'); ?></p>
					<p><strong><?php echo $upload_dir['error']; ?></strong></p>
				</div>

			<?php else : ?>

			<form enctype="multipart/form-data" id="import-upload-form" class="wp-upload-form" method="post" action="<?php echo esc_attr( wp_nonce_url( 'admin.php?import=woocommerce_oei_importer&step=1', 'import-upload' ) ); ?>">
				<p>
				<label for="upload"><?php _e( 'Choose a file from your computer:' ); ?></label> (<?php printf( __('Maximum size: %s' ), $size ); ?>)
				<input type="file" id="upload" name="import" size="25" />
				<input type="hidden" name="action" value="save" />
				<input type="hidden" name="max_file_size" value="<?php echo $bytes; ?>" />
				</p>
				<?php submit_button( __( 'Upload file and import' ), 'primary' ); ?>
			</form>

			<?php
			endif;

		elseif( $step === 1 ) :
			require_once WC_OEI_PLUGIN_DIR . 'includes/admin/class-wc-oei-importer.php';

			$importer = new WC_OEI_Importer;
			$importer->import();

		endif; ?>
	</div>
</div>

<?php

}